### PR TITLE
Precommit: formatting and creation of notebooks/markdown

### PR DESCRIPTION
**Pull request by APJansen**
This PR adds precommit hooks for `JuliaFormatter` and notebook creation, as well as a check on the formatting in the CI.

See [here](https://github.com/DEEPDIP-project/CoupledNODE.jl/blob/precommit/CONTRIBUTING.md) for instructions on how to set it up.

## JuliaFormatter hook
I have used the "official" `JuliaFormatter` hook following [this](https://domluna.github.io/JuliaFormatter.jl/stable/integrations/#Integrations).

It is not as nice as what I'm used to in python with black, in that a. it checks all files rather than only those that have been modified, and b. it doesn't list the files it had to format.

Not a big issue, as long as everyone uses it the only files that it has to modify should be ones you changed, and if you want to see exactly which, you can just do a `git status`.

## notebooks hook

I didn't find any existing hook for this, so I created one that just calls the julia script (changing the the overwrite setting to true). It seems to work fine for me.

## JuliaFormatter CI

Here I also used [the official one](https://github.com/julia-actions/julia-format). It seems overly complicated to me, going through some code checker service reviewdog. Also it doesn't seem to be working, in that it passed on this PR before I applied any formatting.

## Remaining issues
- [x] JuliaFormatter CI
- [x] It is slow enough to be annoying, ~7 seconds for me. Perhaps both hooks do need a check for files that have changed and only be applied there.

### CODE REVIEW

**Comment by APJansen** [comment]
I had to run the formatter in the CI manually as well (i.e. without using the official action), but now it works fine. [here](https://github.com/DEEPDIP-project/CoupledNODE.jl/actions/runs/8436668693/job/23104615163) is an example of what you see on failed formatting: all the changes it made.

**Comment by APJansen** [comment]
I rebased this on main and squashed everything. The only thing that's not working is that it considers also the files in examples/coupling_functions as notebooks, but that's probably best fixed in a separate PR changing the file structure.

**Comment by APJansen** [comment]
sorry one sec, didn't actually rebase on latest main.

**Review by SCiarella — APPROVED** [review]

**Comment by APJansen** [comment]
Can you both check if you can set up pre-commit following the instructions in CONTRIBUTING.md, and if when you run `pre-commit run --all-files` nothing changes? Just to be sure it's correctly reading the settings for everyone.

**Pull request merged**
